stages:
  - build

#job_npl_bmodel:
#  script:
#    - sudo -S su
#    - cd dataplane/npl/bmodel/efcp_router
#    - make build
#    - make test
#  tags: [npl_bmodel]

job_efcp_build:
  script:
    - cd dataplane/p4
    - make efcp-build
#  tags: [build]
  stage: build
  tags: [npl_bmodel]
