# Allow job execution when:
workflow:
  rules:
    # There is a Merge Request against the master branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    # The master branch is building
    - if: $CI_COMMIT_BRANCH == "master"
    # A building process is running
    - if: $CI_JOB_NAME =~ /_build$/
    # The "CRON_AUTO" variable is set (used in scheduled pipelines)
    - if: $CRON_AUTO == "true"
    # ... And do not run automatically if the branch being built is
    # other than master and cron is not running it
    - if: $CI_COMMIT_BRANCH != "master" && $CRON_AUTO != "true"
      when: never

stages:
  - build
  - test
  - cleanup

#
# v1model arch
#

job_efcp_v1model_build:
  script:
    - cd dataplane/p4
    - make efcp-v1model-build
  stage: build
  tags: [p4_v1model]

job_efcp_v1model_cp_test:
  script:
    - sudo -S su
    - cd controlplane/p4
    - make edf-cp-test-stratum
    - cat test/edf-dp-server.log
    - cat test/edf-cp-client.log
  artifacts:
    name: edf_cp_test_${CI_COMMIT_REF_SLUG}
    paths:
      - controlplane/p4/test/edf-*.log
    when: always
    expire_in: 1 week
  dependencies:
    - job_efcp_v1model_build
  stage: test
  tags: [p4_v1model]

job_efcp_v1model_dp_test:
  script:
    - cd dataplane/p4
    - make edf-dp-test-v1model-stratum
    - cat test/arch/v1model/stratum_bmv2_test_h1.log
    - cat test/arch/v1model/stratum_bmv2_test_h2.log
  artifacts:
    name: edf_dp_test_${CI_COMMIT_REF_SLUG}
    paths:
      - dataplane/p4/test/arch/v1model/stratum_bmv2_test_h*.log
    when: always
    expire_in: 1 week
  dependencies:
    - job_efcp_v1model_build
  stage: test
  tags: [p4_v1model]

#
# Tofino arch
#

job_efcp_tna_build:
  script:
    - |
      sudo -H -i -u ubuntu sh -e -x <<EOS
      cd ${PWD}/dataplane/p4
      make efcp-tna-build
      rm -rf pcap_output
      EOS
    - sudo rm -rf dataplane/p4/pcap_output
  stage: build
  tags: [p4_tna]

job_efcp_tna_dp_test:
  script:
    - |
      sudo -H -i -u ubuntu sh -e -x <<EOS
      cd ${PWD}/dataplane/p4
      make edf-dp-test-tna-bfmodel
      EOS
  dependencies:
    - job_efcp_tna_build
  stage: test
  tags: [p4_tna]

job_cleanup:
  script:
    - echo "Cleaning up some intermediate results"
    - sudo rm -rf $CI_PROJECT_DIR
    - sudo rm -rf $BUILD_DIR
    - |
      sudo -H -i sh -e -x <<EOS
      sudo rm -rf ${PWD}/dataplane/p4/pcap_output
      sudo rm -rf ${PWD}/build
      sudo rm -rf $CI_PROJECT_DIR
      sudo rm -rf $CI_PROJECT_DIR
      sudo rm -rf $BUILD_DIR
      EOS
  after_script:
    - sudo rm -rf $CI_PROJECT_DIR
    - sudo rm -rf $BUILD_DIR
    - |
      sudo -H -i sh -e -x <<EOS
      sudo rm -rf ${PWD}/dataplane/p4/pcap_output
      sudo rm -rf ${PWD}/build
      sudo rm -rf $CI_PROJECT_DIR
      sudo rm -rf $BUILD_DIR
      EOS
  stage: cleanup
  tags: [p4_v1model, p4_tna]
