stages:
  - build
  - test
  - clean

job_efcp_v1model_build:
  script:
    - cd dataplane/p4
    - make efcp-v1model-build
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master" && $CRON_AUTO == "true"'
      when: never
    - when: manual
  stage: build
  tags: [npl_bmodel]

job_cp_test:
  script:
    - sudo -S su
    - cd controlplane/p4
    - make edf-cp-test-stratum
    - cat test/edf-dp-server.log
    - cat test/edf-cp-client.log
  dependencies:
    - job_efcp_v1model_build
  rules:
    - when: on_success
  stage: test
  tags: [npl_bmodel]

job_dp_test:
  script:
    - cd dataplane/p4
    - make edf-dp-test-stratum
    - cat test/stratum_bmv2_test_h1.log
    - cat test/stratum_bmv2_test_h2.log
  dependencies:
    - job_efcp_v1model_build
  rules:
    - when: on_success
  stage: test
  tags: [npl_bmodel]
