stages:
  - build
  - test

#job_npl_bmodel:
#  script:
#    - sudo -S su
#    - cd dataplane/npl/bmodel/efcp_router
#    - make build
#    - make test
#  tags: [npl_bmodel]

job_efcp_build:
  script:
    - cd dataplane/p4
    - make efcp-build
#  tags: [build]
  stage: build
  tags: [npl_bmodel]

job_cp_test:
  script:
    - sudo -S su
    - cd controlplane
    - make edf-cp-test
    - cat client/test/edf-cp-server.log
    - cat client/test/edf-cp-client.log
    - rm -rf client/test/*.log
    - cd client/src
    - make clean-deep
    - rm -rf grpc_out
  dependencies:
    - job_efcp_build
  stage: test
#  tags: [test]
  tags: [npl_bmodel]
