#ifdef PROTOBUF_NAMESPACE_ID
#error PROTOBUF_NAMESPACE_ID was previously defined
#endif
#ifndef PROTOBUF_NAMESPACE_ID
#define PROTOBUF_NAMESPACE_ID google::protobuf
#endif

#ifdef GRPC_NAMESPACE_ID
#error GRPC_NAMESPACE_ID was previously defined
#endif
#ifndef GRPC_NAMESPACE_ID
#define GRPC_NAMESPACE_ID grpc
#endif

#ifdef P4_CONFIG_NAMESPACE_ID
#error P4_CONFIG_NAMESPACE_ID was previously defined
#endif
#ifndef P4_CONFIG_NAMESPACE_ID
#define P4_CONFIG_NAMESPACE_ID p4::config::v1
#endif

#ifdef P4_NAMESPACE_ID
#error P4_NAMESPACE_ID was previously defined
#endif
#ifndef P4_NAMESPACE_ID
#define P4_NAMESPACE_ID p4::v1
#endif