/*
 *
 * Copyright 2020 i2CAT.
 *
 * Licensed under ???
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifdef PROTOBUF_NAMESPACE_ID
#error PROTOBUF_NAMESPACE_ID was previously defined
#endif
#ifndef PROTOBUF_NAMESPACE_ID
#define PROTOBUF_NAMESPACE_ID google::protobuf
#endif

#ifdef GRPC_NAMESPACE_ID
#error GRPC_NAMESPACE_ID was previously defined
#endif
#ifndef GRPC_NAMESPACE_ID
#define GRPC_NAMESPACE_ID grpc
#endif

#ifdef P4_CONFIG_NAMESPACE_ID
#error P4_CONFIG_NAMESPACE_ID was previously defined
#endif
#ifndef P4_CONFIG_NAMESPACE_ID
#define P4_CONFIG_NAMESPACE_ID p4::config::v1
#endif

#ifdef P4_NAMESPACE_ID
#error P4_NAMESPACE_ID was previously defined
#endif
#ifndef P4_NAMESPACE_ID
#define P4_NAMESPACE_ID p4::v1
#endif