version: "3"

services:
  mininet:
    container_name: mininet-p4
    hostname: mininet
    image: sergiogimenez/mininet-mod:latest
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
    ports:
      - "50001:50001"
    entrypoint: "/mininet/topo.py"

networks:
  default:
    external:
      name: rina-controlplane
